export interface SchemaEvent {
  description?: string;
  params?: Record<string, string>;
}

export interface Schema {
  events: Record<string, SchemaEvent>;
}

interface TrackerMethod {
  event: SchemaEvent;
  name: string;
  type: "method";
}

interface TrackerNamespace {
  children: Map<string, TrackerEntry>;
  type: "namespace";
}

type TrackerEntry = TrackerMethod | TrackerNamespace;

const identifierPattern = /^[A-Za-z_$][\w$]*$/;

function propertyKey(s: string): string {
  return identifierPattern.test(s) ? s : JSON.stringify(s);
}

function nameToPascal(s: string): string {
  return s
    .split(/[^A-Za-z0-9_$]+|_/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function nameToCamel(s: string): string {
  const pascal = nameToPascal(s);
  const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1);
  return identifierPattern.test(camel) ? camel : `_${camel}`;
}

function trackerPath(name: string): string[] {
  const parts = name.split(".");
  if (parts.some((part) => part.length === 0)) {
    throw new Error(`Event name "${name}" contains an empty namespace segment`);
  }
  return parts.map(nameToCamel);
}

function createTrackerNamespace(): TrackerNamespace {
  return {
    children: new Map(),
    type: "namespace",
  };
}

function insertTrackerEvent(root: TrackerNamespace, name: string, event: SchemaEvent): void {
  const path = trackerPath(name);
  let namespace = root;

  for (const [index, key] of path.entries()) {
    const isMethod = index === path.length - 1;
    const existing = namespace.children.get(key);

    if (isMethod) {
      if (existing) {
        throw new Error(`Event name "${name}" conflicts at tracker path "${path.join(".")}"`);
      }
      namespace.children.set(key, {
        event,
        name,
        type: "method",
      });
      return;
    }

    if (existing?.type === "method") {
      throw new Error(`Event name "${name}" conflicts at tracker path "${path.join(".")}"`);
    }

    if (existing) {
      namespace = existing;
      continue;
    }

    const child = createTrackerNamespace();
    namespace.children.set(key, child);
    namespace = child;
  }
}

function emitTrackerMethod(lines: string[], key: string, method: TrackerMethod, level: number): void {
  const indent = "\t".repeat(level);
  const params = method.event?.params;

  if (method.event?.description) {
    lines.push(`${indent}/** ${method.event.description} */`);
  }
  if (params && Object.keys(params).length > 0) {
    const paramEntries = Object.entries(params);
    const args = paramEntries.map(([k, v]) => `${nameToCamel(k)}: ${v}`).join(", ");
    const obj = paramEntries.map(([k]) => `${propertyKey(k)}: ${nameToCamel(k)}`).join(", ");
    lines.push(`${indent}${propertyKey(key)}(${args}, options?: TrackOptions) {`);
    lines.push(`${indent}\tclient.track("${method.name}", { ${obj} }, options);`);
    lines.push(`${indent}},`);
  } else {
    lines.push(`${indent}${propertyKey(key)}(options?: TrackOptions) {`);
    lines.push(`${indent}\tclient.track("${method.name}", undefined, options);`);
    lines.push(`${indent}},`);
  }
}

function emitTrackerEntry(lines: string[], key: string, entry: TrackerEntry, level: number): void {
  const indent = "\t".repeat(level);
  if (entry.type === "method") {
    emitTrackerMethod(lines, key, entry, level);
    return;
  }

  lines.push(`${indent}${propertyKey(key)}: {`);
  for (const [childKey, child] of entry.children) {
    emitTrackerEntry(lines, childKey, child, level + 1);
  }
  lines.push(`${indent}},`);
}

export function generateTypes(schema: Schema): string {
  const eventNames = Object.keys(schema.events);
  const lines: string[] = ["// @generated by @alyt/codegen — do not edit manually", ""];

  lines.push(
    `export type AnalyticsEventName =\n\t| ${eventNames.map((n) => `"${n}"`).join("\n\t| ")};`,
  );
  lines.push("");
  lines.push("export interface AnalyticsEventMap {");
  for (const [name, def] of Object.entries(schema.events)) {
    if (def?.description) {
      lines.push(`\t/** ${def.description} */`);
    }
    const params = def?.params;
    if (params && Object.keys(params).length > 0) {
      const fields = Object.entries(params)
        .map(([k, v]) => `${propertyKey(k)}: ${v}`)
        .join("; ");
      lines.push(`\t${propertyKey(name)}: { ${fields} };`);
    } else {
      lines.push(`\t${propertyKey(name)}: Record<string, never>;`);
    }
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export function generateTracker(schema: Schema): string {
  const root = createTrackerNamespace();
  for (const [name, def] of Object.entries(schema.events)) {
    insertTrackerEvent(root, name, def);
  }

  const lines: string[] = [
    "// @generated by @alyt/codegen — do not edit manually",
    'import type { AnalyticsClient, TrackOptions } from "@alyt/core";',
    "",
    "export function createTracker(client: AnalyticsClient) {",
    "\treturn {",
  ];

  for (const [key, entry] of root.children) {
    emitTrackerEntry(lines, key, entry, 2);
  }

  lines.push("\t};");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
